# Generated by Django 2.2.10 on 2021-07-17 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_bp', models.CharField(max_length=30)),
                ('ten_bp', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Đợt khám')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('noi_dung', models.TextField(verbose_name='Nộ dung')),
                ('hc_image', models.ImageField(blank=True, default='', null=True, upload_to='assets/images/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='Tài liệu đính kèm')),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Check',
            },
        ),
        migrations.CreateModel(
            name='HealthCheckItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField(verbose_name='STT')),
                ('ho_ten', models.CharField(max_length=200, verbose_name='Họ Tên')),
                ('msnv', models.IntegerField(blank=True, null=True, verbose_name='MSNV')),
                ('ngay_sinh', models.DateField(null=True, verbose_name='Ngày sinh')),
                ('so_bhyt', models.CharField(default='', max_length=30, null=True, verbose_name='Số BHYT')),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=20, null=True, verbose_name='Giới tính')),
                ('cmnd', models.CharField(blank=True, max_length=30, null=True, verbose_name='Số CMND')),
                ('hinh', models.ImageField(blank=True, null=True, upload_to='assets/images/')),
                ('cong_ty', models.CharField(choices=[('VINAWOOD', 'VINAWOOD'), ('Other', 'Other')], default='', max_length=50, verbose_name='Công ty')),
                ('dia_chi', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Địa chỉ')),
                ('so_dt', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Số điện thoại')),
                ('ngay_kham', models.DateField(blank=True, null=True, verbose_name='Ngày khám')),
                ('gio_kham', models.TimeField(blank=True, null=True, verbose_name='Giờ khám')),
                ('gio_ketthuc', models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc')),
                ('status', models.CharField(blank=True, choices=[('DONE', 'DONE'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], max_length=50, null=True, verbose_name='Tình trạng')),
                ('completed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Hoàn tất')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='emp_department', to='hr.Department', verbose_name='Bộ phận')),
                ('healthcheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthcheck', to='hr.HealthCheck')),
            ],
            options={
                'verbose_name': 'Health Check Detail',
                'verbose_name_plural': 'Health Check Detail',
            },
        ),
    ]
