# Generated by Django 3.2.5 on 2021-07-28 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_bp', models.CharField(max_length=30)),
                ('ten_bp', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Đợt khám')),
                ('ngay', models.DateField(verbose_name='Ngày')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('hc_image', models.ImageField(blank=True, default='', null=True, upload_to='assets/images/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='', verbose_name='Tài liệu đính kèm')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Check',
                'verbose_name_plural': 'Health Check',
            },
        ),
        migrations.CreateModel(
            name='HealthCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stt', models.IntegerField(verbose_name='STT')),
                ('ho_ten', models.CharField(max_length=200, verbose_name='Họ Tên')),
                ('msnv', models.IntegerField(blank=True, null=True, verbose_name='MSNV')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=20, null=True, verbose_name='Giới tính')),
                ('so_bhyt', models.CharField(default='', max_length=30, null=True, verbose_name='Số BHYT')),
                ('cmnd', models.CharField(blank=True, max_length=30, null=True, verbose_name='Số CMND')),
                ('cong_ty', models.CharField(choices=[('VINAWOOD', 'VINAWOOD'), ('Other', 'Other')], default='', max_length=100, verbose_name='Công ty')),
                ('dia_chi', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Địa chỉ')),
                ('so_dt', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Số điện thoại')),
                ('ngay_kham', models.DateField(blank=True, null=True, verbose_name='Ngày khám')),
                ('gio_kham', models.TimeField(blank=True, null=True, verbose_name='Giờ khám')),
                ('gio_ketthuc', models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc')),
                ('status', models.CharField(blank=True, choices=[('Chưa tiêm', 'Chưa tiêm'), ('Đã tiêm', 'Đã tiêm'), ('Hoãn tiêm', 'Hoãn tiêm'), ('Không được tiêm', 'Không được tiêm')], max_length=50, null=True, verbose_name='Tình trạng')),
                ('completed', models.BooleanField(blank=True, default=False, null=True, verbose_name='Hoàn tất')),
                ('hc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr.healthcheck')),
            ],
            options={
                'verbose_name': 'Health Check Detail',
                'verbose_name_plural': 'Health Check Detail',
            },
        ),
    ]
