# Generated by Django 2.2.10 on 2021-07-17 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheckitem',
            name='healthcheck',
        ),
        migrations.AddField(
            model_name='healthcheckitem',
            name='hc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr.HealthCheck'),
            preserve_default=False,
        ),
    ]
