# Generated by Django 3.2.5 on 2021-07-17 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0003_auto_20210717_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheck',
            name='created_at',
        ),
        migrations.AddField(
            model_name='healthcheck',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='noi_dung',
            field=models.TextField(verbose_name='Nội dung'),
        ),
    ]
