# Generated by Django 3.2.5 on 2021-07-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_auto_20210718_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckitem',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
