# Generated by Django 3.2.5 on 2021-07-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20210718_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheckitem',
            name='dan_toc',
        ),
        migrations.RemoveField(
            model_name='healthcheckitem',
            name='department',
        ),
        migrations.RemoveField(
            model_name='healthcheckitem',
            name='hinh',
        ),
        migrations.RemoveField(
            model_name='healthcheckitem',
            name='job',
        ),
        migrations.RemoveField(
            model_name='healthcheckitem',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='healthcheckitem',
            name='quoc_tich',
        ),
        migrations.AlterField(
            model_name='healthcheckitem',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
    ]
