# Generated by Django 3.2.5 on 2021-07-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_auto_20210718_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='healthcheckitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='healthcheckitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Đã tiêm', 'Đã tiêm'), ('Hoãn tiêm', 'Hoãn tiêm'), ('Không được tiêm', 'Không được tiêm')], max_length=50, null=True, verbose_name='Tình trạng'),
        ),
    ]
