# Generated by Django 3.2.5 on 2021-07-22 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_auto_20210720_1613'),
        ('hr', '0009_auto_20210720_1640'),
    ]

    operations = [
    ]
