# Generated by Django 3.2.5 on 2021-07-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feet', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Feet')),
                ('inch', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Inch')),
                ('mm', models.IntegerField(blank=True, default=0, null=True, verbose_name='MM')),
                ('freqUsed', models.BooleanField(blank=True, null=True, verbose_name='Freq. used')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=10, verbose_name='Group ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='Group Name')),
                ('sales_target', models.IntegerField(default=0, verbose_name='Sales Target')),
            ],
        ),
        migrations.CreateModel(
            name='SortGroup',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('sym', models.CharField(blank=True, max_length=5, null=True, verbose_name='Sym')),
                ('parent', models.CharField(blank=True, max_length=5, null=True, verbose_name='Parent')),
                ('freqUse', models.BooleanField(blank=True, null=True, verbose_name='Freq Used')),
            ],
        ),
        migrations.CreateModel(
            name='Thick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thick', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Thickness CM')),
                ('mm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='MM')),
                ('inch', models.CharField(max_length=20, verbose_name='Inch')),
            ],
        ),
        migrations.CreateModel(
            name='WoodType',
            fields=[
                ('wood_type_id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Wood type Id')),
                ('sym', models.CharField(blank=True, max_length=5, null=True, verbose_name='Sym')),
                ('description', models.CharField(max_length=200, verbose_name='Name')),
                ('parent_id', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Main group')),
                ('freqUse', models.BooleanField(blank=True, default=True, null=True)),
                ('wood_group', models.CharField(blank=True, choices=[('Main', 'Main'), ('Secondary', 'Secondary')], max_length=20, null=True, verbose_name='WG Type')),
                ('type', models.CharField(blank=True, choices=[('Solid', 'Solid'), ('F/J', 'F/J'), ('F/J Edg', 'F/J Edg')], max_length=10, null=True, verbose_name='Prod Type')),
                ('bod_view', models.BooleanField(blank=True, default=False, null=True, verbose_name='Shown')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profile Group')),
                ('profile_group_description', models.CharField(max_length=200, verbose_name='Group description')),
                ('profile_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Profile ID')),
                ('profile_sym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sym')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/images/master_file', verbose_name='Image')),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Width(mm)')),
                ('thick', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Thick(mm)')),
                ('CBM_Feet', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='CBM/Feet')),
                ('M2_Feet', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='M2/Feet')),
                ('bundle', models.IntegerField(default=0, verbose_name='Pcs/Bundle')),
                ('group_master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_master', to='master_file.profilemaster', verbose_name='Gourp master')),
            ],
        ),
    ]
