# Generated by Django 3.2.5 on 2021-07-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=10, verbose_name='Group ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='Group Name')),
                ('sales_target', models.IntegerField(default=0, verbose_name='Sales Target')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Profile ID')),
                ('profile_sym', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sym')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/images/master_file', verbose_name='Image')),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Width(mm)')),
                ('thick', models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Thick(mm)')),
                ('CBM_Feet', models.DecimalField(decimal_places=9, default=0.0, max_digits=18, verbose_name='CBM/Feet')),
                ('M2_Feet', models.DecimalField(decimal_places=9, default=0.0, max_digits=18, verbose_name='M2/Feet')),
                ('bundle', models.IntegerField(default=0, verbose_name='Pcs/Bundle')),
                ('group_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_master', to='master_file.profilemaster')),
            ],
        ),
    ]
