# Generated by Django 3.2.5 on 2021-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortGroup',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('sym', models.CharField(blank=True, max_length=5, null=True, verbose_name='Sym')),
                ('parent', models.CharField(blank=True, max_length=5, null=True, verbose_name='Parent')),
                ('freqUse', models.BooleanField(blank=True, null=True, verbose_name='Freq Used')),
            ],
        ),
        migrations.CreateModel(
            name='WoodType',
            fields=[
                ('wood_type_id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Wood type Id')),
                ('sym', models.CharField(blank=True, max_length=5, null=True, verbose_name='Sym')),
                ('description', models.CharField(max_length=200, verbose_name='Name')),
                ('parent_id', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Main group')),
                ('freqUse', models.BooleanField(default=True)),
                ('wood_group', models.CharField(blank=True, choices=[('Main', 'Main'), ('Secondary', 'Secondary')], max_length=20, null=True, verbose_name='WG Type')),
                ('type', models.CharField(blank=True, choices=[('Solid', 'Solid'), ('F/J', 'F/J'), ('F/J Edg', 'F/J Edg')], max_length=10, null=True, verbose_name='Prod Type')),
                ('bod_view', models.BooleanField(default=False, verbose_name='Shown')),
            ],
        ),
    ]
