# Generated by Django 3.2.5 on 2021-07-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortgroup',
            name='sym',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sym'),
        ),
    ]
