# Generated by Django 3.2.5 on 2021-07-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0002_alter_sortgroup_sym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortgroup',
            name='parent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent'),
        ),
    ]
