# Generated by Django 3.2.5 on 2021-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0002_sortgroup_woodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodtype',
            name='bod_view',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Shown'),
        ),
        migrations.AlterField(
            model_name='woodtype',
            name='freqUse',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
