# Generated by Django 3.2.5 on 2021-07-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0002_auto_20210729_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Diameter')),
                ('length', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Length')),
                ('BF', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Board FT')),
            ],
            options={
                'ordering': ('dia', 'length'),
            },
        ),
        migrations.AlterModelOptions(
            name='length',
            options={'ordering': ('mm',)},
        ),
        migrations.AlterModelOptions(
            name='thick',
            options={'ordering': ('mm',)},
        ),
        migrations.RemoveField(
            model_name='thick',
            name='id',
        ),
        migrations.AlterField(
            model_name='thick',
            name='mm',
            field=models.DecimalField(decimal_places=2, max_digits=5, primary_key=True, serialize=False, verbose_name='MM'),
        ),
    ]
