# Generated by Django 3.2.5 on 2021-07-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0003_auto_20210730_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thick',
            name='thick',
        ),
        migrations.AddField(
            model_name='thick',
            name='cm',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='CM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thick',
            name='mm',
            field=models.DecimalField(decimal_places=2, max_digits=10, primary_key=True, serialize=False, verbose_name='MM'),
        ),
    ]
