# Generated by Django 3.2.5 on 2021-07-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0003_alter_sortgroup_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodtype',
            name='type',
            field=models.CharField(blank=True, choices=[('Solid', 'Solid'), ('F/J', 'F/J'), ('F/J Edg', 'F/J Edg')], max_length=20, null=True, verbose_name='Prod Type'),
        ),
        migrations.AlterField(
            model_name='woodtype',
            name='wood_group',
            field=models.CharField(blank=True, choices=[('Main', 'Main'), ('Secondary', 'Secondary')], max_length=50, null=True, verbose_name='WG Type'),
        ),
    ]
