# Generated by Django 3.2.5 on 2021-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0004_auto_20210730_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thick',
            name='inch',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inch'),
        ),
    ]
