# Generated by Django 3.2.5 on 2021-07-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0004_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thick', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Thickness CM')),
                ('mm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='MM')),
                ('inch', models.CharField(max_length=20, verbose_name='Inch')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profile Group'),
        ),
    ]
