# Generated by Django 3.2.5 on 2021-07-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0005_auto_20210726_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodtype',
            name='parent_id',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Main group'),
        ),
    ]
