# Generated by Django 3.2.5 on 2021-07-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0005_auto_20210724_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='length',
            name='feet',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name='Feet'),
        ),
        migrations.AlterField(
            model_name='length',
            name='inch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Inch'),
        ),
    ]
