# Generated by Django 3.2.5 on 2021-07-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0005_alter_thick_inch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thick',
            name='mm',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='MM'),
        ),
    ]
