# Generated by Django 3.2.5 on 2021-07-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0006_alter_woodtype_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woodtype',
            name='parent_id',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Main group'),
        ),
    ]
