# Generated by Django 3.2.5 on 2021-07-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0006_auto_20210725_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='length',
            name='freqUsed',
            field=models.BooleanField(default=False, verbose_name='Freq. used'),
        ),
    ]
