# Generated by Django 3.2.5 on 2021-07-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0008_alter_length_freqused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='length',
            name='freqUsed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Freq. used'),
        ),
    ]
