# Generated by Django 3.2.5 on 2021-07-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0008_auto_20210730_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_unit', models.CharField(max_length=20, verbose_name='From unit')),
                ('t_unit', models.CharField(max_length=20, verbose_name='To unit')),
                ('ratio', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Ratio')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_unit', to='master_file.unit', verbose_name='Unit'),
            preserve_default=False,
        ),
    ]
