# Generated by Django 3.2.5 on 2021-07-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0010_auto_20210730_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.IntegerField(default=1, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
