# Generated by Django 3.2.5 on 2021-07-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0011_warehouse_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='name',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
