# Generated by Django 3.2.5 on 2021-07-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0012_auto_20210731_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ('type', 'id')},
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('Wood', 'Wood'), ('Material', 'Material')], max_length=20, verbose_name='Type'),
        ),
    ]
