# Generated by Django 3.2.5 on 2021-07-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0013_auto_20210731_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False, verbose_name='Code'),
        ),
    ]
