# Generated by Django 3.2.5 on 2021-07-31 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_file', '0014_alter_warehouse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitconversion',
            name='f_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_unit', to='master_file.unit', verbose_name='From unit'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='t_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_unit', to='master_file.unit', verbose_name='To unit'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('level', models.IntegerField(default=0, verbose_name='Level')),
                ('parent_id', models.CharField(max_length=100, verbose_name='Parent Category')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Category')),
                ('code', models.CharField(max_length=3, verbose_name='Code')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('useSequence', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('level', 'parent_id', 'id'),
            },
        ),
    ]
