# Generated by Django 3.2.5 on 2021-07-31 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0015_auto_20210731_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='master_file.category', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
