# Generated by Django 3.2.5 on 2021-07-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0016_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('level', 'parent_id', 'id'), 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('sym',), 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent Category'),
        ),
    ]
