# Generated by Django 3.2.5 on 2021-07-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0018_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='parent_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='warehouse_id',
            new_name='warehouse',
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.CharField(default='', max_length=100, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
