# Generated by Django 3.2.5 on 2021-07-31 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0020_auto_20210731_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='master_file.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent_category',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
    ]
