# Generated by Django 3.2.5 on 2021-07-31 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0021_auto_20210731_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
