# Generated by Django 3.2.5 on 2021-08-03 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_file', '0024_auto_20210803_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_group', models.CharField(choices=[('ELEMENT', 'ELEMENT'), ('KEO', 'KEO'), ('PAINT', 'PAINT'), ('STAIN', 'STAIN')], max_length=50, verbose_name='Color Group')),
                ('color_id', models.CharField(max_length=4, verbose_name='Code')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('sort_group_note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sort Group Note')),
                ('gloss', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gloss')),
                ('printed', models.BooleanField(default=False, verbose_name='Printed')),
                ('distressed', models.BooleanField(default=False, verbose_name='Distressed')),
                ('distressed_remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distressed remark')),
                ('phun_hot', models.BooleanField(default=False, verbose_name='Phun hột')),
                ('emboss', models.BooleanField(default=False, verbose_name='Emboss')),
                ('scratch', models.BooleanField(default=False, verbose_name='Scratch')),
                ('glazed', models.BooleanField(default=False, verbose_name='Glazed')),
                ('danh_bui', models.BooleanField(default=False, verbose_name='Đánh bụi')),
                ('remark', models.CharField(max_length=250, verbose_name='Remark')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_creator', to=settings.AUTH_USER_MODEL)),
                ('sort_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='master_file.sortgroup', verbose_name='Sort Group')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_updater', to=settings.AUTH_USER_MODEL)),
                ('wood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='master_file.woodtype', verbose_name='Wood Type')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='master_file.color', verbose_name='Color'),
        ),
    ]
