# Generated by Django 3.2.5 on 2021-08-03 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0025_auto_20210803_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='master_file.sortgroup', verbose_name='Sort Group'),
        ),
    ]
