# Generated by Django 3.2.5 on 2021-08-04 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0028_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sort_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_sortgroup', to='master_file.sortgroup', verbose_name='Sort Group'),
        ),
    ]
