# Generated by Django 3.2.5 on 2021-08-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0029_alter_product_sort_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_group',
            field=models.CharField(choices=[('ELEMENT', 'ELEMENT'), ('KEO', 'KEO'), ('PAINT', 'PAINT'), ('STAIN', 'STAIN'), ('Un_spec', 'Un_spec')], max_length=50, verbose_name='Color Group'),
        ),
    ]
