# Generated by Django 3.2.5 on 2021-08-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0031_alter_color_remark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortgroup',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='color',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
    ]
