# Generated by Django 3.2.5 on 2021-08-05 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0032_auto_20210805_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('color_group', 'color_id'), 'permissions': [('can_edit_color', 'Can edit color'), ('can_delete_color', 'Can delete color')]},
        ),
    ]
