# Generated by Django 3.2.5 on 2021-08-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0034_alter_color_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('color_id',)},
        ),
    ]
