# Generated by Django 3.2.5 on 2021-08-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0036_alter_color_wood_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('term', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Term')),
            ],
        ),
    ]
