# Generated by Django 3.2.5 on 2021-08-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0037_paymentterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterm',
            name='term',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Term'),
        ),
    ]
