# Generated by Django 3.2.5 on 2021-08-05 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_file', '0038_alter_paymentterm_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Bank Code')),
                ('name', models.CharField(max_length=200, verbose_name='Bank Name')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank address')),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank Code')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax')),
            ],
        ),
        migrations.CreateModel(
            name='ShipMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_method', models.CharField(max_length=100, verbose_name='Ship Method')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('tax_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tax code')),
                ('fax_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax No')),
                ('tel_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel. No')),
                ('ext_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ext')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact person')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('deli_term', models.CharField(blank=True, max_length=50, null=True, verbose_name='Deli term')),
                ('bank_acc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account')),
                ('active', models.BooleanField(default=True, verbose_name='Status')),
                ('parent_prefix', models.CharField(max_length=3, verbose_name='Invoice Prefix')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='master_file.bank', verbose_name='Bank Name')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='master_file.country', verbose_name='Country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_creator', to=settings.AUTH_USER_MODEL)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='master_file.partner', verbose_name='Parent')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partners', to='master_file.paymentterm', verbose_name='Payment term')),
                ('ship_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partners', to='master_file.shipmethod', verbose_name='Ship method')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partner_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
