# Generated by Django 3.2.5 on 2021-07-28 06:44

import apps.basic.utilities
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemaster',
            name='group_id',
            field=apps.basic.utilities.UpperCaseCharField(max_length=10, primary_key=True, serialize=False, verbose_name='Group ID'),
        ),
    ]
