# Generated by Django 3.2.5 on 2021-07-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_file', '0002_alter_profilemaster_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemaster',
            name='group_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Group ID'),
        ),
    ]
